# Generated by Django 3.2.3 on 2021-10-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audios',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-created']},
        ),
    ]
