# Generated by Django 3.2.3 on 2021-10-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20211010_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trends',
            options={'ordering': ['-created']},
        ),
    ]
