# Generated by Django 3.2.3 on 2021-10-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_memes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audios',
            old_name='tags',
            new_name='ads',
        ),
        migrations.RenameField(
            model_name='memes',
            old_name='tags',
            new_name='mms',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='tags',
            new_name='vds',
        ),
    ]
